### PR TITLE
Fix the incorrect function in ParamFlowRuleEntity of sentinel-dashboard

### LINKED ISSUE #2174: a mistake function name in class  'ParamFlowRuleEntity'  that will mislead developers
## Issue Description

Type: *bug report* or *feature request*

a mistake

### Describe what happened (or what feature you want)

a function named not in the usual way，and it looks like a mistake that will mislead developers . 

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

### PR DESCRIPTION
**Pull request by jiajiangnan**
### Describe what this PR does / why we need it
the function will mislead developers 

### Does this pull request fix one issue?

Fixes #2174

### Describe how you did it
rename it as a fit name

### CODE REVIEW

**Review by cdfive — APPROVED** [review]
LGTM

**Review by sczyh30 — APPROVED** [review]
LGTM

**Comment by sczyh30** [comment]
Thanks for contributing!

**Comment by jiajiangnan** [comment]
my pleasure

**Pull request merged**
