### PR TITLE
Add timeout "cut-down" mechanism in @SentinelResource annotation

### PR DESCRIPTION
**Pull request by huang054**
### Describe what this PR does / why we need it

Sometimes the system can't respond in time for some reason, like fast failure, service downgrade, user's request will not block all the time.
### Does this pull request fix one issue?
Service downgrade with @SentinelResource without timeout, plus timeout service downgrade

### Describe how you did it
Use the get() time parameter of the future to determine whether it times out

### Describe how to verify it
  @SentinelResource(value = "hello", fallback = "helloFallback",timeOut = 1000)

### CODE REVIEW

**Comment by huang054** [comment]
_
postman
service

_

**Comment by sczyh30** [comment]
Hi, could you please describe what this PR does and why we need it according to the PR template?

**Comment by huang054** [comment]
> 嗨，您能否根据PR模板描述这个PR的作用以及我们为什么需要它？

Sometimes the system can't respond in time for some reason, like fast failure, service downgrade, user's request will not block all the time.

**Comment by sczyh30** [comment]
Thanks for contributing. This kind of "cut-down" mechanism for managed thread pools should be well discussed and designed. Just a managed `SingleThreadExecutor` is not enough.

**Comment by huang054** [comment]
> Thanks for contributing. This kind of "cut-down" mechanism for managed thread pools should be well discussed and designed. Just a managed `SingleThreadExecutor` is not enough.

I am referring to netty to use the cpu core number to set the thread pool size, you mean that the implementation here should reduce the thread hosting use.

**Comment by 0704681032** [comment]
the biz logic will be executed in another thread,is it ok?

**Comment by huang054** [comment]
> the biz logic will be executed in another thread,is it ok?


I  test it success  because the future.get() is blocked.

**Comment by 0704681032** [comment]
when the biz logic code depend on some thread related attribute such as threadlocal,it will be got somthing wrong



---Original---

**Comment by sczyh30** [comment]
Any thoughts on the design? @CarpenterLee @cdfive @jasonjoo2010 @linlinisme

**Comment by jasonjoo2010** [comment]
> Any thoughts on the design? @CarpenterLee @cdfive @jasonjoo2010 @linlinisme

I am agree with @0704681032 , including:

1. Executing in **async way** is implicit if timeout is set to positive value compared to zero. It may lead to bug.

2. Timeout doesn't really mean the execution's termination. Especially we could use rate limiting/threads rules to protect the logic block. So the timeout doesn't make sense to service provider while it often does on calling side(eg. timeout in client / request / consumer in client-server / request-response / consumer-provider model).

3. If we really want the logic block have such kind of timeout we'd better check every invocation's setting carefully (HttpClient / Service Subscription / SQL execution / etc.) or wrap it using Runnable block in any executor simply (It's not a common solution).


These above are my consideration and if anything goes wrong please let me know

**Comment by linlinisme** [comment]
> > Any thoughts on the design? @CarpenterLee @cdfive @jasonjoo2010 @linlinisme
> 
> I am agree with @0704681032 , including:
> 
> 1. Executing in **async way** is implicit if timeout is set to positive value compared to zero. It may lead to bug.
> 2. Timeout doesn't really mean the execution's termination. Especially we could use rate limiting/threads rules to protect the logic block. So the timeout doesn't make sense to service provider while it often does on calling side(eg. timeout in client / request / consumer in client-server / request-response / consumer-provider model).
> 3. If we really want the logic block have such kind of timeout we'd better check every invocation's setting carefully (HttpClient / Service Subscription / SQL execution / etc.) or wrap it using Runnable block in any executor simply (It's not a common solution).
> 
> These above are my consideration and if anything goes wrong please let me know

My suggestion is:
1. Blocked the main thread and wait for another thread pool execute may not be a appropriate. First, blocked main thread is not recommended, why not consider something like reactor way? Second, submit request to another thread pool will reduced  application performance, especially when the request's response is slow, will increase  system burden. And the Thread Pool thread num is hard to decide,  for the compute task and i/o task 's thread num is different.
2. I have a proposal:   Every request  we create a `time-listener`,  it responsible for time-out notify.  And submit to a `ScheduledThreadPoolExecutor` to execute.  When the  'time-listener' task execute, if the request is not completed, execute time out logic. Otherwise, when request completed we `clean` the` time-listener`. It still just a preliminary idea, every one can give you opinion.

**Comment by linlinisme** [comment]
any progress?

**Comment by sczyh30** [comment]
Closing this due to no further feedback. We could discuss the design in #631 if needed.

**Pull request closed without merging**
