### PR TITLE
[feature] Feature #1967 LoginAuthenticationFilter authFilterExcludeUrls match supports uri like /xx/**

### PR DESCRIPTION
**Pull request by brothelul**
### Describe what this PR does / why we need it
LoginAuthenticationFilter authFilterExcludeUrls match supports uri like /xx/**

### Does this pull request fix one issue?

Fixs #1967 

### Describe how you did it
add the `org.springframework.util.AntPathMatcher` to support matching the uri like /xx/**
 
### Describe how to verify it
request the exclude urls

### CODE REVIEW

**Comment by cdfive** [comment]
Good method! How about we apply this new feature? 
In `application.properties`: `auth.filter.exclude-urls=/,/auth/login,/auth/logout,/registry/machine,/version`
`/auth/login,/auth/logout` seems can reduced to `/auth/*`, the other url`/auth/check` can be accessed without login.

**Comment by brothelul** [comment]
it seems can not work ideal with the current excludeUrls, we can keep this feature not change the properties `auth.filter.exclude-urls`. maybe this feature can be apply to the new excludeUrls in the future.

**Review by cdfive — APPROVED** [review]
LGTM. Thanks for contributing and provide this new feature!

**Review by sczyh30 — APPROVED** [review]
LGTM

**Comment by sczyh30** [comment]
Thanks for contributing and look forward to more!

**Pull request merged**
