### PR TITLE
fix flaky test in TracerTest.java

### PR DESCRIPTION
**Pull request by zcai2**
Fixed flaky test that caused by setExceptionPredicate.

For setExceptionsToTrace and setExceptionsToIgnore, if we called setExceptionPredicate first,  it will assigned value to Tracer.exceptionPredicate.

To avoid this case, we would better to reset exceptionPredicate to null first 

The flaky tests are found by running https://github.com/idflakies/iDFlakies

### CODE REVIEW

**Comment by sczyh30** [comment]
Hi, thanks for contributing. Could you please [sign the CLA here](https://cla-assistant.io/alibaba/Sentinel?pullRequest=1859)? And please make sure the email of your commits match your GitHub email. You may refer to the instruction [here](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user), or rebase your commits with the correct email.

---

感谢贡献，请将 commit 对应的 email 调整成与 GitHub 的 email 相匹配并 [确认一下 CLA](https://cla-assistant.io/alibaba/Sentinel?pullRequest=1859)。

**Comment by zcai2** [comment]
Hi,
I have signed the CLA and update my email as well.

**Comment by sczyh30** [comment]
It could be better if you could clear the exceptionPredicate via `@Before` and `@After` period.

**Comment by zcai2** [comment]
clear the exceptionPredicate via @Before and @After period.

**Review by sczyh30 — APPROVED** [review]

**Comment by sczyh30** [comment]
Thanks for contributing!

**Pull request merged**
