### PR TITLE
Fix read file in jar 20190330 dq

### PR DESCRIPTION
**Pull request by dqing0**
### Does this pull request fix one issue?

Fixes https://github.com/alibaba/Sentinel/issues/634

### Describe how you did it
1.参考FileRefreshableDataSource，FileWritableDataSource实现专门读取和写入jar文件的方法
2.通过jdk的JarFile,和jarEntry读取jar包中的文件
3.能够读取jar包中的文件
4.jar包中的文件修改可以更新到内存
5.在控制台更改规则后，能修改本地jar文件中的值

为什么没有通过添加构造器的方法去获取呢？
因为jar文件和普通的文件的读取和写有一些的区别，特别是写，还有classLoader.getResourceAsStream()方法只能获取inputstream对象，只能读取内容，但是它的更新时间获取不到，会导致修改配置文件不能更新规则

### Describe how to verify it
1.运行JarFileDataSourceDemo，JarFileDataSourceInit 中的main方法
2.读取文件内容，修改jar包中的配置文件会更新到内存，在控制台更改规则能更新到本地jar包中的配置文件，
这些功能已验证

### Special notes for reviews
1.写jar包中的某个文件时，其他不用变更的文件也要重写一遍，这点很坑，但jdk提供的JarFile好像只能
这样做，不知道有没有更好的方法取重写jar中的文件

### CODE REVIEW

**Comment by sczyh30** [comment]
Hi, thanks for contributing. One more thing to discuss: is it really necessary to modify the config file inside the jar? I don't think it makes sense to modify files inside the jar because once the jar is upgraded, the files would be lost. Maybe writing to outside files (current implementation) is more appropriate.

What do you think of it? @CarpenterLee @fangjian0423

**Comment by dqing0** [comment]
> files
now,i put the file outside jar.   this way just ，for those who want to configure in jar.  because springboot recommended use jar to run app

**Comment by dqing0** [comment]
And ,According to the original method， if the jar is upgraded, the files also would be lost ,because 
the configuration is  in target classes

**Comment by fangjian0423** [comment]
Sorry for the late reply.

I agree with @sczyh30,  outside file is better than file in jar.

Sorry for the first time I said adding a new constructor in `FileRefreshableDataSource` because check outside file modified is different in jar. Create new datasource is better.

**Comment by sczyh30** [comment]
IMHO, it makes no sense for *dynamic file in jar* as it's not expected to be changed (users cannot modify the file in jar manually). But reading config from the file in jar is okay. So just a `FileInJarReadableDataSource` might be enough (don't need to refresh).

**Comment by dqing0** [comment]
> IMHO, it makes no sense for _dynamic file in jar_ as it's not expected to be changed (users cannot modify the file in jar manually). But reading config from the file in jar is okay. So just a `FileInJarReadableDataSource` might be enough (don't need to refresh).

so,i change my pullrequest,only keep FileInJarReadableDataSource ?

**Comment by sczyh30** [comment]
> > IMHO, it makes no sense for _dynamic file in jar_ as it's not expected to be changed (users cannot modify the file in jar manually). But reading config from the file in jar is okay. So just a `FileInJarReadableDataSource` might be enough (don't need to refresh).
> 
> so,i change my pullrequest,only keep FileInJarReadableDataSource ?

Feel free to do that :)
We can assume that the config file in jar won't be changed, so it don't need to be refreshable.

**Comment by dqing0** [comment]
> We can assume that the config file in jar won't be changed, so it don't need to be refreshable.

ok,i change the pr

**Pull request closed without merging**
