### PR TITLE
Fix typo in the README.md of sentinel-annotation-aspectj

### LINKED ISSUE #1133: README.md description ambiguity
## Issue Description

Filename: sentinel-extension/sentinel-annotation-aspectj/README.md

### Describe what happened (or what feature you want)
Description ambiguity

### Describe what you expected to happen
"runtime waving" need change to "runtime weaving"

### PR DESCRIPTION
**Pull request by zendwind**
### Describe what this PR does / why we need it

fix the README.md ambiguity problem

### Does this pull request fix one issue?

Fixes #1133 

### Describe how you did it

change "time waving" to "time weaving"

note: `weaving` is the terminology of java AOP

### CODE REVIEW

**Comment by sczyh30** [comment]
Hi, thanks for contributing. Could you please [sign the CLA here](https://cla-assistant.io/alibaba/Sentinel?pullRequest=1134)? And please make sure the email of your commits match your GitHub email. You may refer to [the instruction here](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

---

感谢贡献，请将 commit 对应的 email 调整成与 GitHub 的 email 相匹配并 [确认一下 CLA](https://cla-assistant.io/alibaba/Sentinel?pullRequest=1134)。

**Comment by zendwind** [comment]
> he email of your commits match your GitHub email

I have configured the local git email address ,  but for the committed issue that would not link the new email address

**Comment by sczyh30** [comment]
The email of former commits won't be changed, so you may have to rebase your commits, or add your emails according to [the instruction](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by sczyh30** [comment]
You may squash your commits to one commit with the correct email.

**Pull request closed without merging**
