### PR TITLE
Optimize the content ordering of the meta-INF \ Services files in slot to reduce resource waste at load time

### LINKED ISSUE #1648: Optimize the content ordering of the meta-INF \ Services files in slot to reduce resource waste at load time
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
Optimize the content order of the META-INF \ service files in the slot to reduce resource waste at load time, with the expectation that the array will always be the last value inserted, thus reducing consumption

### Describe what you expected to happen
Rearrange them in the order defined，Reduce the waste of resources

### How to reproduce it (as minimally and precisely as possible)

1.Enforcement  `com.alibaba.csp.sentinel.util.SpiLoaderTest#testLoadPrototypeInstanceListSorted`
2. he code will go in `com.alibaba.csp.sentinel.util.SpiLoader.SpiOrderResolver#insertSorted`
3. Loading  `com.alibaba.csp.sentinel.slots.block.authority.AuthoritySlot` when triggered
```java 
private static class SpiOrderResolver {
        private static <T> void insertSorted(List<SpiOrderWrapper<T>> list, T spi, int order) {
            int idx = 0;
            for (; idx < list.size(); idx++) {
                if (list.get(idx).getOrder() > order) {//This is the trigger place
                    break;
                }
            }
            list.add(idx, new SpiOrderWrapper<>(order, spi));
        }
...
}
```

### Tell us your environment
java1.8，sentinel master

### Anything else we need to know?

Only need to modify theMETA-INF/services/com.alibaba.csp.sentinel.slotchain.ProcessorSlot the contents of the order, or to switch to a deque instead

### PR DESCRIPTION
**Pull request by JiangZian**
fix  #1648

### CODE REVIEW

**Comment by sczyh30** [comment]
@JiangZian Could you please remove the changes for `GreetingResourceTest.java`?

**Comment by JiangZian** [comment]
> @JiangZian您可以删除所做的更改`GreetingResourceTest.java`吗？

Ok, I have deleted this change

**Comment by JiangZian** [comment]
> @JiangZian Could you please remove the changes for `GreetingResourceTest.java`?

Ok, I have deleted this change

**Comment by sczyh30** [comment]
Thanks for contributing and look forward to more!

**Pull request merged**
