### PR TITLE
Update Java requirement in the main readme

### LINKED ISSUE #1315: Java version to build?
## Java version question

*feature request*

### Describe what happened (or what feature you want)
When building sentinel-core with Java 1.7 as specified in the sentinel-parent POM and the readme, some dependencies fails as they depend on Java 1.8.

### Describe what you expected to happen
That the build would not fail.

### How to reproduce it (as minimally and precisely as possible)

1. checkout Sentinel repository
2. Set java version to 1.7
3. Run `mvn clean install`

### Tell us your environment
`mvn -v`

Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 1.8.0_241, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"

### PR DESCRIPTION
**Pull request by olof-nord**
Following discussions in https://github.com/alibaba/Sentinel/issues/1315

### Describe what this PR does / why we need it
As currently Java 8 is required to build, I suggest to update the readme accordingly.

### Does this pull request fix one issue?

Fixes #1315 

### Describe how you did it
Not relevant.

### Describe how to verify it
Please see #1315

### CODE REVIEW

**Comment by sczyh30** [comment]
Thanks for your PR. Actually it's not required to be 1.8 if you're just using the Sentinel core jars (sentinel-core, sentinel-transport-common, sentinel-cluster, etc.). It's required to use JDK 1.8 only if you're **building the whole project or the dashboard**.

**Comment by olof-nord** [comment]
I see, thanks for the info. 
My use-case was to build the sentinel-dashboard: and as I do not understand Chinese the main readme file was my only source of information.

**Comment by sczyh30** [comment]
> I see, thanks for the info.
> My use-case was to build the sentinel-dashboard: and as I do not understand Chinese the main readme file was my only source of information.

Actually we have English wiki here: https://github.com/alibaba/Sentinel/wiki/Dashboard
But indeed it's necessary to point out that the dashboard only supports JDK 1.8 in the README :) Could you please improve the README.md about it?

**Comment by sczyh30** [comment]
Hi, any update?

**Comment by olof-nord** [comment]
> Hi, any update?

Hello! As the Wiki got updated, I am not sure how important it is to also mention it in the main readme. Updated my suggestion according to our discussion.

**Comment by sczyh30** [comment]
Thanks!

**Pull request merged**
