### PR TITLE
Feature: Make transport-netty-http/transport-simple-http support posting

### PR DESCRIPTION
**Pull request by jasonjoo2010**
Make transport layer support parameters in post body

### Describe what this PR does / why we need it
include `netty-http` and `simple-http`

### Does this pull request fix one issue?
#618

### CODE REVIEW

**Comment by jasonjoo2010** [comment]
Because another unstable unit test `WarmUpRateLimiterControllerTest` this PR also make it stable to pass travis

**Comment by sczyh30** [comment]
> Because another unstable unit test `WarmUpRateLimiterControllerTest` this PR also make it stable to pass travis

👍

**Comment by sczyh30** [comment]
Seems that `ClusterNodeTest.testGetOrCreateOriginNodeMultiThread` is also unstable. I think it might be caused by [line 98](https://github.com/alibaba/Sentinel/blob/master/sentinel-core/src/test/java/com/alibaba/csp/sentinel/node/ClusterNodeTest.java#L97-L104): 

```java
Node node = clusterNode.getOrCreateOriginNode(origins.get(random.nextInt(origins.size())));
```

The line will get origin randomly from the `origin` array. In rare circumstances, not all origins can be visited.

**Comment by jasonjoo2010** [comment]
> Seems that `ClusterNodeTest.testGetOrCreateOriginNodeMultiThread` is also unstable. I think it might be caused by [line 98](https://github.com/alibaba/Sentinel/blob/master/sentinel-core/src/test/java/com/alibaba/csp/sentinel/node/ClusterNodeTest.java#L97-L104):
> 
> ```java
> Node node = clusterNode.getOrCreateOriginNode(origins.get(random.nextInt(origins.size())));
> ```
> 
> The line will get origin randomly from the `origin` array. In rare circumstances, not all origins can be visited.

Yeah, i found i seems like suffering unstable tests now

**Comment by jasonjoo2010** [comment]
> Seems that `ClusterNodeTest.testGetOrCreateOriginNodeMultiThread` is also unstable. I think it might be caused by [line 98](https://github.com/alibaba/Sentinel/blob/master/sentinel-core/src/test/java/com/alibaba/csp/sentinel/node/ClusterNodeTest.java#L97-L104):
> 
> ```java
> Node node = clusterNode.getOrCreateOriginNode(origins.get(random.nextInt(origins.size())));
> ```
> 
> The line will get origin randomly from the `origin` array. In rare circumstances, not all origins can be visited.

I think in rare condition this random algorithm may miss the assertion.

eg.

What is expected as: 

origin | count
--- | ---
origin1 | 7
origin2 | 7
origin3 | 6

But maybe happen:

origin | count
--- | ---
origin1 | 10
origin2 | 10
origin3 | 0

And it will fail.

Should we consist on the random algorithm and introduce sth. like `Set` to indicate what has been actually hit or just make it a `RoundRobin` like algorithm?

**Comment by sczyh30** [comment]
> > Seems that `ClusterNodeTest.testGetOrCreateOriginNodeMultiThread` is also unstable. I think it might be caused by [line 98](https://github.com/alibaba/Sentinel/blob/master/sentinel-core/src/test/java/com/alibaba/csp/sentinel/node/ClusterNodeTest.java#L97-L104):
> > ```java
> > Node node = clusterNode.getOrCreateOriginNode(origins.get(random.nextInt(origins.size())));
> > ```
> > 
> > 
> > The line will get origin randomly from the `origin` array. In rare circumstances, not all origins can be visited.
> 
> I think in rare condition this random algorithm may miss the assertion.
> 
> eg.
> 
> What is expected as:
> 
> origin	count
> origin1	7
> origin2	7
> origin3	6
> But maybe happen:
> 
> origin	count
> origin1	10
> origin2	10
> origin3	0
> And it will fail.
> 
> Should we consist on the random algorithm and introduce sth. like `Set` to indicate what has been actually hit or just make it a `RoundRobin` like algorithm?

Yes, maybe we can just make it a round robin (`taskCount / originSize`).

**Comment by jasonjoo2010** [comment]
Done with it.

And it's strange only this PR suffers unstable unit tests frequently.

**Comment by sczyh30** [comment]
Good job. Unstable test cases often fail when merging into master (and we have to manually restart the CI job to retry)

**Comment by sczyh30** [comment]
Seems that the CLA status is expired? Could you please check the CLA status of your GitHub account?

**Comment by jasonjoo2010** [comment]
> Seems that the CLA status is expired? Could you please check the CLA status of your GitHub account?

It's just because default email is internal address and i forgot to override it when commit.

Now it's ok

**Comment by sczyh30** [comment]
Nice work. Thanks for contributing!

**Comment by cdfive** [comment]
@jasonjoo2010 @sczyh30 Oh, I'm sorry for make `ClusterNodeTest.testGetOrCreateOriginNodeMultiThread ` unstable, neglecting the random rare condition. Thanks to fix it!

**Pull request merged**
