### PR TITLE
Upgrade fastjson to 1.2.58

### PR DESCRIPTION
**Pull request by cat-coco**
### Describe what this PR does / why we need it
fastjson version is too lower, it has security problem and cause the project compile failed

### Does this pull request fix one issue?
yes 

### Describe how you did it
Upgrade fastjson to 1.2.58

### CODE REVIEW

**Comment by sczyh30** [comment]
Hi, thanks for contributing. Could you please [sign the CLA here](https://cla-assistant.io/alibaba/Sentinel?pullRequest=949)? And please make sure the email of your commits match your GitHub email.

Please make sure your commit message is written in English.

---

感谢贡献，请将 commit 对应的 email 调整成与 GitHub 的 email 相匹配并 [确认一下 CLA](https://cla-assistant.io/alibaba/Sentinel?pullRequest=949)。

**Comment by cat-coco** [comment]
> Hi, thanks for contributing. Could you please [sign the CLA here](https://cla-assistant.io/alibaba/Sentinel?pullRequest=949)? And please make sure the email of your commits match your GitHub email.
> 
> Please make sure your commit message is written in English.
> 
> 感谢贡献，请将 commit 对应的 email 调整成与 GitHub 的 email 相匹配并 [确认一下 CLA](https://cla-assistant.io/alibaba/Sentinel?pullRequest=949)。

check it ,already send the CLA

**Comment by sczyh30** [comment]
Please make sure the email of your commits matches your GitHub email. You may refer to https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

**Comment by cat-coco** [comment]
> Please make sure the email of your commits matches your GitHub email. You may refer to https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

check it again.aleady send the CLA and the email is correct

**Comment by sczyh30** [comment]
image

你这个 commit 对应的 email 和你 GitHub 账号里面设置的 email 不匹配。git log 看一下是哪个 email，然后在 GitHub setting 里面添加一下。

**Pull request closed without merging**
