### PR TITLE
Fix NPE in LogSlot#entry for recording rule ID

### PR DESCRIPTION
**Pull request by ZebulonFeng**
### Describe what this PR does / why we need it
Fix NPE in LogSlot#entry, it will make system rule config not take effect.

### CODE REVIEW

**Comment by ZebulonFeng** [comment]
@sczyh30  Previous email address is invalid，I've made a new PR.

**Review by sczyh30 — APPROVED** [review]
LGTM

**Comment by sczyh30** [comment]
Thanks for contributing!

**Comment by brucelwl** [comment]
> 

这个修复治标不治本, SystemBlockException 中根本就没有添加 Rule, id获取到的永远是null, 需求:https://github.com/alibaba/Sentinel/issues/2851

**Comment by sczyh30** [comment]
Refer #3148, #3143

**Comment by zhangbao283** [comment]
这个bug1.8.6还没修复吗

**Pull request merged**
