### PR TITLE
Complete the unit tests for sentinel-logging-slf4j

### PR DESCRIPTION
**Pull request by jasonjoo2010**
### Describe what this PR does / why we need it
Previous implementations of unit tests for sentinel-logging-slf4j can not be run normally.
But it's important to have the ability of testing.
A new dependency `slf4j-test` is introduced to replace log4j2 implementation to make testing reliable.

## When reviewing
Please notice that there is a previous PR related: #1355 
And when it's approved and merged i will rebase it up to date.

### CODE REVIEW

**Comment by jasonjoo2010** [comment]
Branch has been rebased and again CI report an error with skipping.

**Comment by sczyh30** [comment]
Cool. Thanks!

**Comment by cdfive** [comment]
Awesome! And should the `sentinel-demo-log-logback` module based on this?
Using it to demo the usage.
```
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-logging-slf4j</artifactId>
    <version>${sentinel.version}</version>
</dependency>
```

**Comment by jasonjoo2010** [comment]
> Awesome! And should the `sentinel-demo-log-logback` module based on this?
> Using it to demo the usage.
> 
> ```
> <dependency>
>     <groupId>com.alibaba.csp</groupId>
>     <artifactId>sentinel-logging-slf4j</artifactId>
>     <version>${sentinel.version}</version>
> </dependency>
> ```

Oh i think it should be another like `sentinel-demo-log-slf4j` or you are talking about this PR #1356 

And integrations of logging are designed so simple that is it necessary to write a demo? After all all steps should take is to introduce a new dependency. 
And i don't know more logging supports like `console` / `file` should also be migrated into sentinel-logging module to make them more explicit. Just a proposal based on "Introduce it when you need it" instead of more configurations.

**Comment by cdfive** [comment]
Quite agree with you, "Introduce it when you need it"!
Now the `sentinel-logging-slf4j` module makes it simple to use logback,log4j and other log framework based slf4j. 

BTW, I learned to write unit tests through abstract classes. Thanks! @jasonjoo2010

**Comment by jasonjoo2010** [comment]
> Quite agree with you, "Introduce it when you need it"!
> Now the `sentinel-logging-slf4j` module makes it simple to use logback,log4j and other log framework based slf4j.
> 
> BTW, I learned to write unit tests through abstract classes. Thanks! @jasonjoo2010

I am glad that something can be useful to you :)

**Pull request merged**
