### PR TITLE
Upgrade Dubbo version in sentinel-demo-dubbo

### PR DESCRIPTION
**Pull request by Leishunyu**
dubbo version change ,old dubbo demo can't import DubboComponentScan on dubbo 2.6.2
I change the version to dubbo 2.6.5

### CODE REVIEW

**Comment by Leishunyu** [comment]
@sczyh30 can you help me review

**Comment by sczyh30** [comment]
Hi, could you please sign the CLA here: https://cla-assistant.io/alibaba/Sentinel?pullRequest=436

**Comment by Leishunyu** [comment]
> Hi, could you please sign the CLA here: https://cla-assistant.io/alibaba/Sentinel?pullRequest=436

OK,3q

**Comment by sczyh30** [comment]
Thanks for contributing!

**Pull request merged**
