### PR TITLE
bugfix:rocketmq demo can not finish

### LINKED ISSUE #1651: 关于rocketmq demo问题
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
在运行SyncProducer和PullConsumerDemo程序时，抛出异常，但是运行并未结束。
以下分别两个类运行的截图
image

image

### Describe what you expected to happen
希望deno运行异常时，正常结束程序

### Tell us your environment
master分支

### PR DESCRIPTION
**Pull request by PeineLiang**
### Describe what this PR does / why we need it
The rocketmq demo unable to run and stop because of miss namesrv configuration, and now fixed.

### Does this pull request fix one issue?
Fixes #1651

### CODE REVIEW

**Comment by sczyh30** [comment]
Hi, could you please add some PR descriptions?

**Comment by PeineLiang** [comment]
> Hi, could you please add some PR descriptions?

added, please check it.

**Review by sczyh30 — APPROVED** [review]
LGTM

**Comment by sczyh30** [comment]
Thanks for contributing!

**Pull request merged**
