### PR TITLE
 Modify variable names and Optimize methods

### PR DESCRIPTION
**Pull request by yidadi**
Modify variable names and Optimize methods

### CODE REVIEW

**Comment by sczyh30** [comment]
Hi, could you please illustrate why these changes are necessary?

**Comment by yidadi** [comment]
This method #resolveSlotChainBuilder just get the first SlotChainBuilder from the list.

**Comment by sczyh30** [comment]
Maybe your change is not compatible with the current design:

> - If there is no user-defined `SlotChainBuilder`, then use the default slot chain builder
> - If user-defined `SlotChainBuilder` exists, the provider will pick the first loaded customized slot chain builder, then cache the builder.


See #145 for details.

**Comment by yidadi** [comment]
Why? Is it necessary to put an object in a list and get only the first one?

**Comment by sczyh30** [comment]
The list was initially designed for different strategies (e.g. pick the first customized, pick the final customized or ordered by `@SpiOrder`) but is not actually used indeed... I think it's okay to remove the list, but support for `@SpiOrder` should also be considered (we could leverage the `SpiLoader` class). For further improvement of the slot SPI, we could refer to #316

**Comment by sczyh30** [comment]
Thanks!

**Pull request merged**
