### PR TITLE
[ISSUE #2425] upgrade the nacos client version to 1.4.2.

### LINKED ISSUE #2425: nacos 使用参数NACOS_AUTH_ENABLE=true之后，sentinel无法读取配置信息。请问这个怎么解决啊？
如题

### PR DESCRIPTION
**Pull request by brotherlu-xcq**
### Describe what this PR does / why we need it

upgrade the nacos client version to 1.4.2.

### Does this pull request fix one issue?

Fixes #2425

### CODE REVIEW

**Review by sczyh30 — COMMENTED** [review]
Maybe keeping changes only for `sentinel-datasource-nacos` module is better? This could make the commits pure (other enhancements could be carried in another PRs)

**Comment by brotherlu-xcq** [comment]
because when I upgrade the nacos version, the common-lang3 package is removed too, so I change the unit test.

**Comment by sczyh30** [comment]
> because when I upgrade the nacos version, the common-lang3 package is removed too, so I change the unit test.

Then that's okay.

**Review by sczyh30 — APPROVED** [review]
LGTM

**Comment by sczyh30** [comment]
Thanks for contributing!

**Pull request merged**
