### PR TITLE
Prometheus metric extension

### PR DESCRIPTION
**Pull request by CarpenterLee**
Signed-off-by: Carpenter Lee <hooleeucas@163.com>

### Describe what this PR does / why we need it
Sentinel real-time statistics are useful for system monitoring. #730 adds extension interface to Sentinel internal statistics, which provides an implementation independent way to get Sentinel statistics.

This PR provides Prometheus backend implementation of `MetricExtension`. 

### Does this pull request fix one issue?

NONE

### Describe how you did it
Provides Prometheus backend implementation of `MetricExtension`. 

### Describe how to verify it
Run test cases.

### CODE REVIEW

**Comment by sczyh30** [comment]
Related to #211

**Comment by anjia0532** [comment]
Has there been any progress in this matter?

**Comment by Billzaifei** [comment]
Hi, @CarpenterLee
I think the extension still need to improve. It should provide some kind of tags to distinguish from provider metrics from consumer ones.In my practice, the two metrics always make me confused.

**Comment by Billzaifei** [comment]
Hi, @sczyh30 !  Is my request(#1566 ) closed?

**Comment by sczyh30** [comment]
> #1566

This PR is outdated. New PRs are welcomed!

**Comment by Billzaifei** [comment]
> > Hi, @sczyh30 ! Is my request(#1566 ) closed?
> > Issue Description
> > Type: feature request
> > Describe what happened (or what feature you want)
> > For the below interface, I used it to export prometheus metrics.
> > com.alibaba.csp.sentinel.metric.extension.MetricExtension
> > Take the method[addPass(String resource, int n, Object... args)] for example.
> > I want to distinguish [in] type from [out] type using it as the prometheus tag. #provider[in]/consumer[out]
> > So I think I need a feature replacing the input String parameter[resource] with the below class type:
> > com.alibaba.csp.sentinel.slotchain.ResourceWrapper
> 
> This PR is outdated. New PRs are welcomed!

Enhancement/advanced metric extension tagging entrytype #1609 raised for the feature request#1566

**Comment by wushengju** [comment]
I have try this way to send Metric to prometheus, but i can't find metics like sentinel_pass_requests_total in http://localhost:9527/actuator/prometheus.

**Pull request closed without merging**
