### PR TITLE
Fixes Issues #1696 添加持久化支持，可选持久化选项：nacos、apollo、zookeeper ; 修改 README.md 说明文档

### PR DESCRIPTION
**Pull request by jiajiangnan**
Signed-off-by: jiajiangnan <jiajiangnan.office@foxmail.com>

Fixes Issues #1696
1、添加持久化支持，可选持久化选项：nacos、apollo、zookeeper
2、修改 README.md 和 Sentinel_Dashboard_Feature.md 说明文档

### Describe what this PR does / why we need it

Extended persistence module. We can persistent the configs of rules into config-center like nacos,apollo,zookeeper. It can make sure the rule configs could make work even if we restart the sentinel-dashbord or sentinel client in applications. Now，this PR is also adapte to the web views，the views is not needed to modify at all.

### Does this pull request fix one issue?

Fixes Issues #1696

### Describe how you did it

1、Add config items in springboot config files such as application.properties. These config items is the settings that config-center needed. When sentinel-dashboard is starting, Spring will identify which config-center is configed, or used the memory as the default store.
2、All kinds of config-center has it's self Rules ManageClient which constructed by @configuration, but only one will be construct by sentinel-dashboard started because the @configuration has condition. The only one is that be configed in application.preperties. We can manage the rules through ManageClient.
3、There is a condition sentences to ensure that the old code still worked. If the item added in application is memory, then use the default "sentinelApiClient", else use the Client constructed by @configuration.

### Describe how to verify it

Before：
1、add the following config items in application.properties:
datasource.provider=nacos
datasource.provider.nacos.server-addr=ip:port
2、run sentinel-dashboard
3、application which inclues sentinel-client ，config to the same config-center

After：
1、manage rules in sentinel-dashboard, search the configs in config-center, do some request in application which inclues sentinel-client
2、manage rules in config-center, search the rules in dashboard, do some request in application which inclues sentinel-client
3、Because of this PR has adapt the default memory store，and also adapt the web view, so we can test directly in the old web pages.

### Special notes for reviews

1、this PR has adapt the default memory store，and also adapt the web view, so we can test directly in the old web pages.

### CODE REVIEW

**Comment by jiajiangnan** [comment]
different kind of config-center has it's own config items, details in the follow Pic from “Sentinel_Dashboard_Feature.md”. Please review code and do some test , Thanks.
68F338C8-2FBC-443D-82AF-F8BFB0F29DA7

**Comment by jiajiangnan** [comment]
different kind of config-center has it's own config items, details in the follow pic has added into “Sentinel_Dashboard_Feature.md”.
Please review code and do some test , Thanks.
68F338C8-2FBC-443D-82AF-F8BFB0F29DA7

**Comment by jiajiangnan** [comment]
different kind of config-center has it's own config items, details in the follow pic has added into “Sentinel_Dashboard_Feature.md”.
Please review code and do some test , Thanks.
68F338C8-2FBC-443D-82AF-F8BFB0F29DA7

**Comment by jiajiangnan** [comment]
has commit the Properties file that was forgotten to committed, which will cause rules couldn't persist into datassource of config-center. So sorry for it.

**Comment by jiajiangnan** [comment]
has commit the Properties file that was forgotten to commit, which will cause rules couldn't persist into datassource of config-center. So sorry for it.

**Comment by jiajiangnan** [comment]
@sczyh30 Could you please take a time to help review the code？ Thanks ~

**Comment by lly835** [comment]
没人管了？

**Comment by ConnorLH** [comment]
搞不懂为什么官方不添加持久化功能的神操作啊，开源虽然是阉割版，但是dashboard应该是生产可用的啊。

**Comment by slin1972** [comment]
以jar启动  不兼容-D的配置方式?  修改代码里面的application.properties启动OK

**Comment by slin1972** [comment]
@jiajiangnan 
得通过spring的参数声明方式  
如下:
java -Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=sentinel-dashboard -jar sentinel-dashboard.jar --datasource.provider=nacos --datasource.provider.nacos.server-addr=localhost:8844 --datasource.provider.nacos.username=nacos --datasource.provider.nacos.password=nacos --datasource.provider.nacos.namespace=d296f6d7-559c-4430-9c20-b9ec9db58342

**Comment by slin1972** [comment]
你确定你这个PR是可用的吗？ @jiajiangnan 
我现在遇到了一个问题， 已经存在持久化的规则，无法push到应用，配置无效，而且新增规则也是无效？
无效是指规则无法在应用生效

但是如果我不启用nacos的数据源，则是OK的

**Comment by slin1972** [comment]
目前测试 是可用的

**Comment by wenbochang888** [comment]
mark

**Comment by wenbochang888** [comment]
> 目前测试 是可用的

@slin1972 启动不知道为什么不兼容-D。

我试了试 --datasource.provider=nacos 这种方式，目前zk报错

```
2021-04-06 19:58:44.970  WARN 5029 --- [           main] o.a.zookeeper.client.StaticHostProvider  : No IP address found for server: localhhost:2181

java.net.UnknownHostException: localhhost: Name or service not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929) ~[na:na]
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515) ~[na:na]
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298) ~[na:na]

```

**Comment by wenbochang888** [comment]
```
@Configuration
@ConditionalOnProperty(prefix = DataSourceProperties.PREFIX_DATASOURCE, name = DataSourceProperties.NAME_PROVIDER, havingValue = DataSourceProperties.VALUE_PROVIDER_ZOOKEEPER, matchIfMissing = false)
public class ZookeeperConfiguration {

    @Autowired
    private ZookeeperProperties zookeeperProperties;

    @Bean
    public CuratorFramework zkClient() {
        ExponentialBackoffRetry exponentialBackoffRetry =  new ExponentialBackoffRetry(zookeeperProperties.getBaseSleepTime(), zookeeperProperties.getMaxRetries(), zookeeperProperties.getMaxSleepTime());
        CuratorFramework zkClient = CuratorFrameworkFactory.newClient("localhhost:2181", exponentialBackoffRetry);
        zkClient.start();
        return zkClient;
    }
} 
```
 CuratorFramework zkClient = CuratorFrameworkFactory.newClient("localhhost:2181", exponentialBackoffRetry);
这一块是bug把，怪不得不能用-D

**Comment by kuangyoubo** [comment]
When will this feature be available? Too slow.

**Comment by 350478992** [comment]
我以为过去一年了，应该合并到分支release了吧，进来一看，还是open的呀，失望。。。

**Comment by ruoshuixuelabi** [comment]
一年多了，是什么原因导致没合并到master分支呢？

**Comment by kuangyoubo** [comment]
代码能给我一下吗？


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: ruoshuixuelabi ***@***.***&gt;
发送时间: 2021年9月10日 15:57
收件人: alibaba/Sentinel ***@***.***&gt;
抄送: kuangyoubo ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[alibaba/Sentinel] Fixes Issues #1696 添加持久化支持，可选持久化选项：nacos、apollo、zookeeper ; 修改 README.md 说明文档 (#1711)





 
一年多了，是什么原因导致没合并到master分支呢？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kuangyoubo** [comment]
> 一年多了，是什么原因导致没合并到master分支呢？

你那个分支是哪一个，我看看

**Comment by kuangyoubo** [comment]
> 一年多了，是什么原因导致没合并到master分支呢？



> 代码已提交，麻烦 review

@jiajiangnan 你那个分支是哪一个，我看看

**Comment by zznan0o0** [comment]
@slin1972 你那个方式是修改源码之后的还是官方打包的jar包就已经支持了呢？

**Pull request closed without merging**
