### PR TITLE
doc:fix typo in README.md(#1925)

### PR DESCRIPTION
**Pull request by evasnowind**
### Describe what this PR does / why we need it
fix a typo in README

### Does this pull request fix one issue?
Yes, this fix the issue 1925, see https://github.com/alibaba/Sentinel/issues/1925

### CODE REVIEW

**Comment by sczyh30** [comment]
Could you please sign the CLA here: https://cla-assistant.io/alibaba/Sentinel?pullRequest=1926

**Comment by evasnowind** [comment]
> Could you please sign the CLA here: https://cla-assistant.io/alibaba/Sentinel?pullRequest=1926

Yes, I have signed just now.

**Comment by evasnowind** [comment]
If there is anything I can do, let me know, thx.

**Comment by evasnowind** [comment]
I have signed just now. If there is anything I need to do, let me know, thx.

**Review by sczyh30 — APPROVED** [review]
LGTM

**Comment by sczyh30** [comment]
Thanks for contributing!

**Pull request merged**
