### PR TITLE
修正closeResources方法中无法打印首次异常

### PR DESCRIPTION
**Pull request by hongpy**
修改closeResources方法中的if判断

### CODE REVIEW

**Comment by sczyh30** [comment]
Could you please sign the CLA here: https://cla-assistant.io/alibaba/Sentinel?pullRequest=2890

**Comment by sczyh30** [comment]
It could be better if you could add test cases for it as well.

**Review by cdfive — APPROVED** [review]
LGTM. Thanks for pointing it out and help fixing it! @hongpy @sczyh30

**Comment by sczyh30** [comment]
Thanks for contributing!

**Pull request merged**
