### PR TITLE
fix concurrentHashMap get and put in large numbers concurrency

### PR DESCRIPTION
**Pull request by samuelxw**
fix concurrentHashMap get and put in large numbers concurrency when MetricFetcher handler response from client

### CODE REVIEW

**Comment by samuelxw** [comment]
代码已提交，麻烦 review

**Review by cdfive — APPROVED** [review]
LGTM

**Comment by cdfive** [comment]
The `map` in `handleBody` method is `ConcurrentHashMap`, I suddenly found that it was a local variable, which declared in 
`fetchOnce` method, `fetchOnce->handleResponse->handleBody`, does it affects multithreading safety and performance?

Anyway, using `computeIfAbsent`, it is at least a kind of optimization, which simplifies the writing method and enhances the readability.

**Comment by cdfive** [comment]
> fix concurrentHashMap get and put in large numbers concurrency when MetricFetcher handler response from client

Oh, `in large numbers concurrency`, the size of map may be too big, `computeIfAbsent` is better than `get` and `put`?

If we make sure it's a local variable, how about we use `LinkedHashMap` instead of `ConcurrentHashMap`? since `LinkedHashMap` use default `computeIfAbsent` method in `Map` interface.

How do you think about it? @samuelxw @linlinisme @jasonjoo2010 @sczyh30

**Comment by cdfive** [comment]
Sorry, I didn't read it carefully. Although it is a local variable in the fetchonce method, it is shared by multiple threads.

**Pull request merged**
