### PR TITLE
[feat #1839]: Support setting server.servlet.context-path

### PR DESCRIPTION
**Pull request by xuande**
[#1839](https://github.com/alibaba/Sentinel/issues/1839)

### Describe what this PR does / why we need it
Sentinel dashboard support setting `server.servlet.context-path`

### Does this pull request fix one issue?
NONE

### Describe how you did it
增加`<base href="">`标签, http请求时增加baseUrl，解决增加contextPath后请求路径仍然是绝对路径问题

### Describe how to verify it
启动时增加`--server.servlet.context-path=/sentinel`，访问`http://localhost:8080/sentinel`能够正常访问

### CODE REVIEW

**Review by jasonjoo2010 — CHANGES_REQUESTED** [review]
It looks good after an overviewing.
But you should also regenerate/update `dist/js/app.js` using gulp.
Please take the document in `webapp/resources` as a reference.
And furthermore, I suffered some trouble updating them at first. In my environment, it could be fixed by upgrading to gulp 4.x. So If you are not familiar with / meet other problems please let me know that.

**Comment by xuande** [comment]
> It looks good after an overviewing.
> But you should also regenerate/update `dist/js/app.js` using gulp.
> Please take the document in `webapp/resources` as a reference.
> And furthermore, I suffered some trouble updating them at first. In my environment, it could be fixed by upgrading to gulp 4.x. So If you are not familiar with / meet other problems please let me know that.

`dist/js/app.js` has been committed, and I executed the gulp command build without any problems.
`dist/js/app.js`已提交，我执行gulp命令构建时没有遇到问题.

**Review by jasonjoo2010 — APPROVED** [review]
I have no question now.

LGTM

**Comment by jasonjoo2010** [comment]
Thanks for contributing.

**Pull request merged**
