### PR TITLE
feat: sentinel can feel exception though application has configured E…

### PR DESCRIPTION
**Pull request by 24kpure**
Describe what this PR does / why we need it
sentinel can feel exception though application has configured ExceptionHandler

Does this pull request fix one issue?
https://github.com/alibaba/Sentinel/issues/3141
https://github.com/alibaba/Sentinel/pull/3149

Describe how you did it
Add a class SentinelExceptionAware which implement HandlerExceptionResolver and put exception into request.

Describe how to verify it
UT & add it in my project

Special notes for reviews
Thanks for your work.

### CODE REVIEW

**Comment by 24kpure** [comment]
@sczyh30 @jasonjoo2010 @brotherlu-xcq @LearningGp
I have raised mr(https://github.com/alibaba/Sentinel/pull/3149) for a year so that sentinel default branch changed to 1.8.
Maybe reviewer can be faster this time,thanks~

**Comment by 24kpure** [comment]
@sczyh30 @jasonjoo2010 @brotherlu-xcq @LearningGp
I have raised mr(https://github.com/alibaba/Sentinel/pull/3149) for a year so that sentinel default branch changed to 1.8.
Maybe reviewer can be faster this time,thanks~

**Comment by 24kpure** [comment]
@sczyh30 @jasonjoo2010 @brotherlu-xcq @LearningGp
I have raised mr(https://github.com/alibaba/Sentinel/pull/3149) for a year so that sentinel default branch changed to 1.8.
Maybe reviewer can be faster this time,thanks~

**Comment by 24kpure** [comment]
As a mature open source project, PR should be handled in a timely manner, rather than being shelved year after year. I am not sure whether this project is still maintained, or only people within Alibaba can get the review. Open source is not just for KPI, at least there should be enthusiasm, right?

**Comment by LearningGp** [comment]
> As a mature open source project, PR should be handled in a timely manner, rather than being shelved year after year. I am not sure whether this project is still maintained, or only people within Alibaba can get the review. Open source is not just for KPI, at least there should be enthusiasm, right?

I'm sorry, this was indeed my oversight. The review for this PR has already been completed in the related PR, and it can be merged directly.

**Comment by 24kpure** [comment]
Apologize for my recklessness. I still like sentinel ~

**Pull request merged**
