### PR TITLE
[up]去除异常提示

### PR DESCRIPTION
**Pull request by zhaoyunxing92**

### CODE REVIEW

**Comment by sczyh30** [comment]
Hi, thanks for contributing. Could you please describe what this PR does / why we need it in the PR description? And have you ever verified your changes?

**Comment by zhaoyunxing92** [comment]
> 嗨，谢谢你的贡献。您能否在PR描述中描述这个公关做了什么/我们为什么需要它？你有没有验证过你的变化？



> Hi, thanks for contributing. Could you please describe what this PR does / why we need it in the PR description? And have you ever verified your changes?

我验证过了,主要是对.jshintrc文件提示的异常做出的处理,以及忽略`alert`语法的校验

**Comment by sczyh30** [comment]
Could you please sign the CLA here: https://cla-assistant.io/alibaba/Sentinel?pullRequest=763

**Comment by sczyh30** [comment]
Friendly ping: Could you please sign the CLA here: https://cla-assistant.io/alibaba/Sentinel?pullRequest=763

**Pull request closed without merging**
