### PR TITLE
Support async servlet (3.0 and above)

### LINKED ISSUE #306: 异步Servlet支持？
## 比如使用案例如下
```java
@RestController
public class AsyncController {

    @GetMapping("/async")
    public CompletableFuture<String> async() {

        return CompletableFuture.supplyAsync(() -> {

                    try {
                        TimeUnit.SECONDS.sleep(1);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    return "async\";
                }
        );

    }

}
```

### PR DESCRIPTION
**Pull request by jasonjoo2010**
# Brief

### Describe what this PR does / why we need it
Support async servlet requests.

### Does this pull request fix one issue?

Resolves #306 

### Describe how to verify it
Support async servlet under servlet >= 3.0

### Special notes for reviews
Compatibility under servlet <= 2.5

# Async Servlet Support
After servlet 3.0 async servlet is supported for slow request. So sentinel's servlet adapter should support it and keep backward compatibility.  

But there may be difference between implementations of servlet. Generally there are two kinds of flow for async requests.

## Normal Request Flow
For normal request the flow is shown below:  
normalrequestflow

### Tomcat
For async servlet in containers like tomcat the flow is like:  
asyncrequestflow1

### Spring Boot or Mock
For async servlet in some special implementation things changed:  
asyncrequestflow2

## Design
So in `CommonFilter` we should deal with several scenarios:

* Judge a request entering async pool by calling `isAsyncStarted`(since servlet 3.0).
* Register a listener for async servlets to exit their sentinel contexts.
* Trace `timeout` and `error` in the listeners for sentinel.
* Handle the reentering filters of async servlet in some implementations. Separate them from fresh requests.

To make sure backward compatibility we can use `reflection`. All reflections are cached for better performance.

### CODE REVIEW

**Comment by sczyh30** [comment]
Hi, thanks for contributing. The implementation is cool, but as it leverages reflection to invoke methods about async Servlet, will it affect the performance?

**Comment by sczyh30** [comment]
And could you please illustrate your design in the description?

**Comment by jasonjoo2010** [comment]
> Hi, thanks for contributing. The implementation is cool, but as it leverages reflection to invoke methods about async Servlet, will it affect the performance?

That was quite some days ago and i will try a different path. So is the the design.
I will fill it later.

**Comment by jasonjoo2010** [comment]
> And could you please illustrate your design in the description?

More details have been put into the Description and also been put into the subfolder in `README`.

And change the `inAsync` judgement into another efficient way.

Please check and drop your further reviews back when you have time.

**Comment by sczyh30** [comment]
> > And could you please illustrate your design in the description?
> 
> More details have been put into the Description and also been put into the subfolder in `README`.
> 
> And change the `inAsync` judgement into another efficient way.
> 
> Please check and drop your further reviews back when you have time.

👍 Cool, I'll review it later.

**Comment by sczyh30** [comment]
@jasonjoo2010 Could you please fix the conflict?

**Comment by jasonjoo2010** [comment]
> @jasonjoo2010 Could you please fix the conflict?

Yep, they have been fixed. And I add two new protected methods for tests. And fix some deprecated code under new version of `JUnit`.

Does it need more tests?

**Pull request closed without merging**
