### PR TITLE
Remove redundant semicolon in MetricWriter

### LINKED ISSUE #410: Redundant semicolon in com.alibaba.csp.sentinel.node.metric.MetricWriter class
// 在第349行多了为分号.位于方法closeAndNewFile内.

## Issue Description
In the 349th line, there is more a semicolon. It is located in the method closeAndNewFile.

Type: *bug report* or *feature request*
bug report
### Describe what happened (or what feature you want)
find it in the code

### Describe what you expected to happen
Remove any extra semicolons

### How to reproduce it (as minimally and precisely as possible)

in the code

### Tell us your environment

win7 idea
### Anything else we need to know?
no

### PR DESCRIPTION
**Pull request by kangyl**
### Describe what this PR does / why we need it
it's unnecessary  code

### Does this pull request fix one issue?
Fixes #410

### Describe how you did it
remove the unnecessary  semicolon

### Describe how to verify it
in the com.alibaba.csp.sentinel.node.metric.MetricWriter  349th line

### Special notes for reviews
no

### CODE REVIEW

**Comment by kangyl** [comment]
我是说明我CLA没有签署是吗?是不是只要将阿里巴巴开原协议签署后发送到opensource@alibaba-inc.com就可以了?

**Comment by sczyh30** [comment]
Hi, thanks for contributing.  You can [sign the CLA here](https://cla-assistant.io/alibaba/Sentinel?pullRequest=412). And please make sure the email of your commits match your GitHub email.

---

感谢贡献，请将 commit 对应的 email 调整成与 GitHub 的 email 相匹配并 [确认一下 CLA](https://cla-assistant.io/alibaba/Sentinel?pullRequest=412)。

**Comment by sczyh30** [comment]
And could you please edit the PR description according to the [PR template](https://github.com/alibaba/Sentinel/blob/master/.github/PULL_REQUEST_TEMPLATE.md)? Some contribution guidelines here: https://github.com/alibaba/Sentinel/wiki/%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97

**Comment by kangyl** [comment]
> Hi, thanks for contributing. You can [sign the CLA here](https://cla-assistant.io/alibaba/Sentinel?pullRequest=412). And please make sure the email of your commits match your GitHub email.
> 
> 感谢贡献，请将 commit 对应的 email 调整成与 GitHub 的 email 相匹配并 [确认一下 CLA](https://cla-assistant.io/alibaba/Sentinel?pullRequest=412)。

我已经确认CLA了,邮件也已经设置,但是 [请将 commit 对应的 email 调整成与 GitHub 的 email 相匹配]这个不是很明白,需要重新提交吗?

**Comment by sczyh30** [comment]
> > Hi, thanks for contributing. You can [sign the CLA here](https://cla-assistant.io/alibaba/Sentinel?pullRequest=412). And please make sure the email of your commits match your GitHub email.
> > 感谢贡献，请将 commit 对应的 email 调整成与 GitHub 的 email 相匹配并 [确认一下 CLA](https://cla-assistant.io/alibaba/Sentinel?pullRequest=412)。
> 
> 我已经确认CLA了,邮件也已经设置,但是 [请将 commit 对应的 email 调整成与 GitHub 的 email 相匹配]这个不是很明白,需要重新提交吗?

你本地 Git 配置的 email (`git config --global user.email xxx@aaa.com`) 和 GitHub 上面的 email 不匹配，因此无法识别。可以重新配置 Git email 后 rebase 重新提交一下。

**Comment by sczyh30** [comment]
Thanks for contributing!

**Pull request merged**
