### PR TITLE
remove unused code

### PR DESCRIPTION
**Pull request by John-Chan**
Signed-off-by: cj <power4j@outlook.com>

### Describe what this PR does / why we need it
Remove unused code from [TokenServerHandler.java](https://github.com/alibaba/Sentinel/blob/c5da3faad995deba8bacc7368ae874749dca8238/sentinel-cluster/sentinel-cluster-server-default/src/main/java/com/alibaba/csp/sentinel/cluster/server/handler/TokenServerHandler.java#L50)

### Does this pull request fix one issue?

NONE

### CODE REVIEW

**Comment by yunfeiyanggzq** [comment]
LGTM

**Comment by sczyh30** [comment]
@John-Chan Could you please sign the CLA here: https://cla-assistant.io/alibaba/Sentinel?pullRequest=1667

**Comment by John-Chan** [comment]
I have signed the CLA @sczyh30

**Comment by sczyh30** [comment]
Thanks for contributing and look forward to more!

**Pull request merged**
