### PR TITLE
Clear useless data in ParameterMetric for removed rules

### PR DESCRIPTION
**Pull request by wavesZh**
### Describe what this PR does / why we need it

we should clear metric for nonexistent param rule for some reasons:

1. Reduce memory footprint.
2. The service runs for a while then readd the rule after deleting the rule, if happening outbreak request，we expected that blocked, but in fact that will pass, because token bucket algorithm in ParamFlowChecker#passDefaultLocalCheck: 

```java
long toAddCount = (passTime * tokenCount) / (rule.getDurationInSec() * 1000);
long newQps = toAddCount + restQps > maxCount ? (maxCount - acquireCount) : (restQps + toAddCount - acquireCount);
```

### Does this pull request fix one issue?

NONE

### Describe how you did it

clear when loading rules.

### Describe how to verify it

unit test

### CODE REVIEW

**Comment by sczyh30** [comment]
Actually it's not thread-safe when accessing the counter map. We may need to improve it later (using copy-on-write mechanism).

**Comment by wavesZh** [comment]
I will improve it in this pr.

**Comment by sczyh30** [comment]
> I will improve it in this pr.

Just open another PR to improve it (and it could be better to create an issue :)

**Comment by sczyh30** [comment]
Thanks for contributing!

**Pull request merged**
