### PR TITLE
Apply p3c pmd plugin/rules and fix/ignore all violations of priority 1

### LINKED ISSUE #573: Follow alibaba coding guidelines
## Issue Description

*feature request*

### Describe what happened (or what feature you want)

This repo doesn't follow the coding guidelines of https://github.com/alibaba/p3c

### Describe what you expected to happen

It should.

### How to reproduce it (as minimally and precisely as possible)

N/A

### Tell us your environment

N/A

### Anything else we need to know?

N/A

### PR DESCRIPTION
**Pull request by blindpirate**
### Describe what this PR does / why we need it

This PR applies alibaba p3c pmd plugin/rules and fixes all violations of priority 1.

### Does this pull request fix one issue?

Fixes #573 

### Describe how you did it

Just fix all violations.

### Describe how to verify it

 ```
mvn clean install -DskipTests -DminimumPriority=1
```

### CODE REVIEW

**Comment by blindpirate** [comment]
Seems like some tests are behaving flaky: `WarmUpRateLimiterControllerTest` and `OccupiableBucketLeapArrayTest`. With nearly same code, [1st build](https://travis-ci.org/alibaba/Sentinel/builds/506536432) and [2nd build](https://travis-ci.org/alibaba/Sentinel/builds/506543878) fail but [3rd build](https://travis-ci.org/alibaba/Sentinel/builds/506554488) succeeds. 

Are there any known issues? Please let me know if you need me to investigate.

**Comment by sczyh30** [comment]
> Seems like some tests are behaving flaky: `WarmUpRateLimiterControllerTest` and `OccupiableBucketLeapArrayTest`. With nearly same code, [1st build](https://travis-ci.org/alibaba/Sentinel/builds/506536432) and [2nd build](https://travis-ci.org/alibaba/Sentinel/builds/506543878) fail but [3rd build](https://travis-ci.org/alibaba/Sentinel/builds/506554488) succeeds.
> 
> Are there any known issues? Please let me know if you need me to investigate.

It's a known issue that some sleep-based test cases are not stable. See #541 for discussion.

**Comment by blindpirate** [comment]
Thanks! @sczyh30

**Comment by sczyh30** [comment]
Thanks for contributing!

**Comment by blindpirate** [comment]
Thanks!

**Pull request merged**
