### PR TITLE
[Fixes #1538] Upgrade fastjson to 1.2.71

### LINKED ISSUE #1538: Upgrade fastjson to 1.2.71
## Issue Description

Type: *dependency upgrade*

### Describe what happened (or what feature you want)

Upgrade fastjson to the latest version to reduce security vulnerability.

### PR DESCRIPTION
**Pull request by J-Cod3r**
### Does this pull request fix one issue?
Fixes [#1538](https://github.com/alibaba/Sentinel/issues/1538)

### CODE REVIEW

**Comment by yunfeiyanggzq** [comment]
LGTM,But I think you'd  better rebase your three commits to a commit.

**Comment by sczyh30** [comment]
Since [fastjson 1.2.71](https://github.com/alibaba/fastjson/releases/tag/1.2.71) has just been released, we may upgrade to 1.2.71.

**Comment by yunfeiyanggzq** [comment]
please change the tittle ` Upgrade fastjson to 1.2.70 ` ->` Upgrade fastjson to 1.2.71 `

**Comment by yunfeiyanggzq** [comment]
LGTM

**Comment by J-Cod3r** [comment]
> Since [fastjson 1.2.71](https://github.com/alibaba/fastjson/releases/tag/1.2.71) has just been released, we may upgrade to 1.2.71.

Done

**Comment by sczyh30** [comment]
Thanks!

**Pull request merged**
